// Curated database of well-known opening tricks/traps.
// Each entry sets up a position from the starting position via `setupMoves`
// (SAN played alternately by both sides) and asks the user to play
// `userMove` from their side. `alternatives` are also accepted as correct
// answers. `continuation` is played out after a correct move to show the
// payoff/refutation.
//
//   category: "defend" — the opponent is trying to trick you, find the
//                        prevention move so you don't lose material/get mated
//             "attack" — the opponent has just blundered, find the punish
//   tier:     S/A/B/C/D/F  — same scale as openings (S = essential to know)

const TRICKS = [
  {
    id: "scholars-mate",
    name: "Scholar's Mate",
    eco: "C20",
    category: "defend",
    setupMoves: ["e4","e5","Bc4","Nc6","Qh5"],
    userColor: "black",
    userMove: "g6",
    alternatives: ["Qe7","Qf6"],
    continuation: ["Qf3","Nf6"],
    description: "White is going for the 4-move checkmate — queen and bishop both eyeing f7. Defend f7 and attack the queen.",
    why: "g6 attacks the queen and defends f7 in one move. After Qf3 Black plays Nf6 calmly developing; White's early queen sortie has wasted tempo.",
    tier: "S",
    popularity: 4
  },
  {
    id: "wayward-queen",
    name: "Wayward Queen Attack",
    eco: "C20",
    category: "defend",
    setupMoves: ["e4","e5","Qh5"],
    userColor: "black",
    userMove: "Nc6",
    alternatives: [],
    continuation: ["Bc4","g6","Qf3","Nf6"],
    description: "White's queen is out early hunting the e5 pawn. Don't grab a free piece — develop, defend, and make White's queen pay for moving too soon.",
    why: "Nc6 calmly defends e5 and develops. Anything that drops the e5 pawn (or plays ...Qf6 blocking the f-pawn) lets White seize the initiative.",
    tier: "A",
    popularity: 4
  },
  {
    id: "damiano-defense",
    name: "Damiano's Defense",
    eco: "C40",
    category: "attack",
    setupMoves: ["e4","e5","Nf3","f6"],
    userColor: "white",
    userMove: "Nxe5",
    alternatives: [],
    continuation: ["fxe5","Qh5+"],
    description: "Black has played the dubious 2...f6 — known as Damiano's Defense and one of the oldest losing lines in chess. Find the punishment.",
    why: "After Nxe5 fxe5, Qh5+ wins. If g6, Qxe5+ forks king and rook. If Ke7, Qxe5+ also picks up the rook later. Black's structure is shattered.",
    tier: "A",
    popularity: 3
  },
  {
    id: "fried-liver",
    name: "Fried Liver Attack",
    eco: "C57",
    category: "defend",
    setupMoves: ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","d5","exd5"],
    userColor: "black",
    userMove: "Na5",
    alternatives: ["Nd4","b5"],
    continuation: ["Bb5+","c6","dxc6","bxc6"],
    description: "White is set up to sac a knight on f7 (Fried Liver / Lolli Attack). Recapturing the d5 pawn with the knight walks into Nxf7! — find the Polerio Defense.",
    why: "Na5 attacks the Bc4 and avoids the Nxf7 sac entirely. Nxd5 instead leads to 6.Nxf7 Kxf7 7.Qf3+ and White has a dangerous attack for the piece.",
    tier: "S",
    popularity: 4
  },
  {
    id: "englund-qb4",
    name: "Englund Gambit · Qb4+",
    eco: "A40",
    category: "attack",
    setupMoves: ["d4","e5","dxe5","Nc6","Nf3","Qe7","Bf4"],
    userColor: "black",
    userMove: "Qb4+",
    alternatives: [],
    continuation: ["Bd2","Qxb2","Bc3","Bb4"],
    description: "White has developed naturally but the queen has been left on the long diagonal to b2. Black has a forcing shot.",
    why: "Qb4+ forks the king and the b2 pawn. After Bd2 Qxb2 Black has won a pawn with active piece play; the natural-looking Bf4 was a trap.",
    tier: "A",
    popularity: 3
  },
  {
    id: "legal-trap",
    name: "Légal Trap",
    eco: "C41",
    category: "defend",
    setupMoves: ["e4","e5","Nf3","Nc6","Bc4","d6","Nc3","Bg4","h3"],
    userColor: "black",
    userMove: "Bxf3",
    alternatives: ["Bh5","Bd7","Be6"],
    continuation: ["Qxf3","Nf6"],
    description: "White has kicked the bishop with h3. The famous Légal mate punishes ...Bh5?? with 6.Nxe5! winning. Find a safe move for the bishop.",
    why: "Bxf3 (or simply retreating with Bd7 / Be6) sidesteps the trap. Naive piece preservation with ...Bh5 walks into 6.Nxe5! Bxd1 7.Bxf7+ Ke7 8.Nd5#.",
    tier: "S",
    popularity: 3
  },
  {
    id: "blackburne-shilling",
    name: "Blackburne Shilling Gambit",
    eco: "C50",
    category: "defend",
    setupMoves: ["e4","e5","Nf3","Nc6","Bc4","Nd4"],
    userColor: "white",
    userMove: "Nxd4",
    alternatives: ["O-O","c3","d3"],
    continuation: ["exd4"],
    description: "Black's third knight move offers the e5 pawn. It's a trap — taking with the knight loses on the spot. Find the calm refutation.",
    why: "Nxd4 simply trades knights with no fuss. The seductive Nxe5?? loses to Qg5! forking the knight on e5 and the g2 pawn (and threatening Qxg2#).",
    tier: "A",
    popularity: 3
  },
  {
    id: "elephant-trap",
    name: "Elephant Trap (QGD)",
    eco: "D51",
    category: "attack",
    setupMoves: ["d4","d5","c4","e6","Nc3","Nf6","Bg5","Nbd7","cxd5","exd5","Nxd5"],
    userColor: "black",
    userMove: "Nxd5",
    alternatives: [],
    continuation: ["Bxd8","Bb4+","Qd2","Bxd2+","Kxd2","Kxd8"],
    description: "White has just played Nxd5 thinking the knight on f6 is pinned by Bg5. But it isn't really — Black wins a piece.",
    why: "Nxd5 Bxd8 Bb4+! exploits the loose Bg5. After the forced trades Black emerges a full piece up. A textbook trap every Queen's Gambit player should know.",
    tier: "A",
    popularity: 3
  },
  {
    id: "petroff-d6",
    name: "Petroff Defense · d6 first",
    eco: "C42",
    category: "defend",
    setupMoves: ["e4","e5","Nf3","Nf6","Nxe5"],
    userColor: "black",
    userMove: "d6",
    alternatives: [],
    continuation: ["Nf3","Nxe4"],
    description: "Mirror moves so far. The natural-looking Nxe4 is a mistake — find the prophylactic move first.",
    why: "d6 kicks the knight before recapturing. Symmetric Nxe4?? loses to Qe2! pinning, and if Black moves the knight Qxe4+ regains material with a winning position (Marshall's Trap).",
    tier: "A",
    popularity: 4
  },
  {
    id: "marshall-petroff",
    name: "Marshall Trap (Petroff)",
    eco: "C42",
    category: "attack",
    setupMoves: ["e4","e5","Nf3","Nf6","Nxe5","Nxe4"],
    userColor: "white",
    userMove: "Qe2",
    alternatives: [],
    continuation: ["Nf6","Nc6+"],
    description: "Black has copied your knight move into the center — but symmetry breaks here. Find the discovered-check trick.",
    why: "Qe2 pins the e4 knight. Any normal knight retreat (like Nf6) gets hit by Nc6+ — a discovered check unmasking the queen on e-file. Black drops the queen.",
    tier: "A",
    popularity: 3
  },
  {
    id: "noahs-ark",
    name: "Noah's Ark Trap",
    eco: "C77",
    category: "attack",
    setupMoves: ["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","d6","d4","b5","Bb3","Nxd4","Nxd4","exd4","Qxd4"],
    userColor: "black",
    userMove: "c5",
    alternatives: [],
    continuation: ["Qd5","Be6","Qc6+","Bd7","Qd5","c4"],
    description: "Classic Ruy Lopez trap. White's queen on d4 looks centralized but the Bb3 is dangerously close to being trapped on the queenside. Find the lever.",
    why: "c5 chases the queen and starts the net around Bb3. After the queen retreats and Black plays ...c4, the bishop has no escape squares — locked in like Noah's Ark.",
    tier: "B",
    popularity: 2
  },
  {
    id: "traxler",
    name: "Traxler Counterattack",
    eco: "C57",
    category: "attack",
    setupMoves: ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7"],
    userColor: "black",
    userMove: "Bxf2+",
    alternatives: [],
    continuation: ["Kxf2","Nxe4+","Kg1","Qh4"],
    description: "White has grabbed the f7 pawn with the knight. Instead of recapturing, Black has a much sharper continuation.",
    why: "Bxf2+! is the brilliant Traxler counter — refusing to recapture and going for the king. After Kxf2 Nxe4+ Kg1 Qh4, Black has a furious attack worth far more than the sacrificed piece.",
    tier: "A",
    popularity: 3
  },
  {
    id: "lasker-trap",
    name: "Lasker Trap (Albin Counter-Gambit)",
    eco: "D08",
    category: "attack",
    setupMoves: ["d4","d5","c4","e5","dxe5","d4","e3","Bb4+","Bd2","dxe3","Bxb4","exf2+","Ke2"],
    userColor: "black",
    userMove: "fxg1=N+",
    alternatives: [],
    continuation: ["Rxg1","Bg4+","Ke1","Bxd1"],
    description: "White has played the natural-looking 4.e3 — a known mistake. The follow-up requires Black to find one of the rarest moves in chess.",
    why: "fxg1=N+! Underpromote to a knight — promoting to a queen lets White swap with Rxg1 and Black is fine but unspectacular. The knight gives check and then ...Bg4+ traps White's queen on d1.",
    tier: "B",
    popularity: 2
  },
  {
    id: "kieninger",
    name: "Kieninger Trap (Budapest)",
    eco: "A52",
    category: "attack",
    setupMoves: ["d4","Nf6","c4","e5","dxe5","Ng4","Bf4","Nc6","Nf3","Bb4+","Nbd2","Qe7","a3","Ngxe5","axb4"],
    userColor: "black",
    userMove: "Nd3#",
    alternatives: [],
    continuation: [],
    description: "White has grabbed Black's bishop with axb4 — and it's mate in one. Find the smothered-king finish.",
    why: "Nd3#! The knight forks the king and the only piece that could capture (the e-pawn) is pinned by Black's queen on e7. Every escape square is occupied by White's own pieces.",
    tier: "A",
    popularity: 3
  },
  {
    id: "stafford-bxf2",
    name: "Stafford Gambit · Bxf2+ mate",
    eco: "C42",
    category: "attack",
    setupMoves: ["e4","e5","Nf3","Nc6","Nxe5","Nf6","Nxc6","dxc6","d3","Bc5","Bg5","Nxe4","Bxd8"],
    userColor: "black",
    userMove: "Bxf2+",
    alternatives: [],
    continuation: ["Ke2","Bg4#"],
    description: "White has snatched the queen — but Black has a forced mate. The Stafford Gambit's most famous trap.",
    why: "Bxf2+! Ke2 (forced — Kxf2 loses to Nxd1) Bg4# — the bishop pair criss-crosses the white king and mate is delivered with Black's queen long gone.",
    tier: "B",
    popularity: 3
  },
  {
    id: "mortimer",
    name: "Mortimer Trap (Ruy Lopez)",
    eco: "C65",
    category: "defend",
    setupMoves: ["e4","e5","Nf3","Nc6","Bb5","Nf6","O-O","Ne7"],
    userColor: "white",
    userMove: "Re1",
    alternatives: ["d4","Nc3","d3"],
    continuation: ["c6","Bc4","Ng6"],
    description: "Black has played the strange-looking ...Ne7. It's a trap — grabbing the e5 pawn loses material. Find a calm developing move.",
    why: "Re1 (or any sensible developing move) refuses the bait. Nxe5?? c6! traps the bishop: Bc4 (or anywhere) is met by ...Qa5! winning the bishop or worse.",
    tier: "B",
    popularity: 2
  },
  {
    id: "fishing-pole",
    name: "Fishing Pole Trap",
    eco: "C65",
    category: "defend",
    setupMoves: ["e4","e5","Nf3","Nc6","Bb5","Nf6","O-O","Ng4","h3","h5"],
    userColor: "white",
    userMove: "d3",
    alternatives: ["Re1","c3","Bxc6"],
    continuation: ["Nf6","Re1"],
    description: "Black has offered the knight twice in a row. Greedy capture loses to a king-side mating attack — find the developing move.",
    why: "Anything except 6.hxg4. After hxg4?? hxg4 the h-file opens for Black's queen with deadly threats of ...Qh4 and ...g3 — White has no defense against the mating net.",
    tier: "B",
    popularity: 3
  },
  {
    id: "kgd-qh4",
    name: "King's Gambit Declined · Qh4+",
    eco: "C30",
    category: "attack",
    setupMoves: ["e4","e5","f4","Bc5","fxe5"],
    userColor: "black",
    userMove: "Qh4+",
    alternatives: [],
    continuation: ["Ke2","Qxe4+"],
    description: "White has greedily taken the e5 pawn — opening a fatal diagonal toward the king. Find the punishment.",
    why: "Qh4+! White's king has no safe square — Ke2 walks into Qxe4+ regaining the piece with a near-winning attack. g3 is met by Qxe4+ winning the rook on h1.",
    tier: "B",
    popularity: 2
  },
  {
    id: "caro-fantasy",
    name: "Caro-Kann Fantasy · Qh4+",
    eco: "B12",
    category: "attack",
    setupMoves: ["e4","c6","d4","d5","f3","e5","dxe5"],
    userColor: "black",
    userMove: "Qh4+",
    alternatives: [],
    continuation: ["g3","Qxe4+"],
    description: "White has weakened the e1-h4 diagonal with f3 and now grabbed the e5 pawn. Find Black's free shot.",
    why: "Qh4+! exploits the f3 weakness. g3 (forced) Qxe4+ wins back the pawn with active queen play — Black is already better.",
    tier: "B",
    popularity: 2
  },
  {
    id: "halloween",
    name: "Halloween Gambit refutation",
    eco: "C46",
    category: "defend",
    setupMoves: ["e4","e5","Nf3","Nc6","Nc3","Nf6","Nxe5","Nxe5","d4"],
    userColor: "black",
    userMove: "Ng6",
    alternatives: ["Nc6"],
    continuation: ["e5","Ng8"],
    description: "White has sacrificed a knight for two central pawns (the Halloween Gambit). The natural-looking retreat is the wrong one — find the right knight square.",
    why: "Ng6 keeps the extra piece while frustrating White's attack. Other retreats let White build a powerful center with e5 and easy development for the sacrificed material.",
    tier: "C",
    popularity: 2
  },
  {
    id: "latvian-qg5",
    name: "Latvian Gambit · Qg5 fork",
    eco: "C40",
    category: "attack",
    setupMoves: ["e4","e5","Nf3","f5","Bc4","fxe4","Nxe5"],
    userColor: "black",
    userMove: "Qg5",
    alternatives: [],
    continuation: ["Nf7","Qxg2"],
    description: "White has gone in for the e5 pawn — but the knight is now hanging and the g2 pawn is undefended. Find the fork.",
    why: "Qg5! attacks the knight on e5 and the g2 pawn. White can't defend both: Nxf7 Qxg2 wins the rook on h1 with a crushing attack.",
    tier: "C",
    popularity: 2
  }
];

if (typeof window !== "undefined") {
  window.TRICKS = TRICKS;
}
